backend:
  name: git-gateway

  branch: main # Branch to update (optional; defaults to master)

media_folder: 'assets/uploads'

collections:
  - name: 'website-settings'
    label: 'Настройки'
    files:
      - label: "Новости"
        name: "news"
        file: "_data/news.yml"
        fields:
          - label: "Новости"
            name: "news"
            allow_add: true
            add_to_top: true
            max: 4
            min: 1
            widget: "list"
            fields:
              - {label: "Заголовок новости", name: "header", widget: "string"}
              - {label: "Описание", name: "disc", widget: "text"}
              - {label: "Картинка", name: "img", widget: "image"}
      - label: "Сотрудники"
        name: "instructors"
        file: "_data/instructors.yml"
        fields:
          - label: "Сотрудники"
            name: "instructors"
            allow_add: true
            add_to_top: true
            max: 15
            min: 1
            widget: "list"
            fields:
              - {label: "Имя", name: "name", widget: "string"}
              - {label: "О сотруднике", name: "disc", widget: "text"}
              - {label: "Картинка", name: "img", allow_multiple: false, widget: "image"}
              - label: "Виды спорта"
                name: "kind-of-sports"
                allow_add: true
                add_to_top: true
                max: 6
                widget: "list"
                fields:
                  - label: "Название вида спорта" 
                    name: "label" 
      - label: "Изменить контактные данные"
        name: "contact-info"
        file: "_data/contact-info.yml"
        fields:
          - {label: "E-mail", name: "e-mail", widget: "string"}
          - {label: "Телефон", name: "tel", widget: "string"}
      - label: "Загрузить/изменить документы"
        name: "sections"
        file: "_data/documents.yml"
        fields:
          - label: "Документы"
            name: "sections"
            allow_add: true
            add_to_top: true
            widget: "list"
            fields:
              - label: "Название блока документов"
                name: "header"
                widget: "string"
              - label: "Документ"
                name: "documents"
                allow_add: true
                add_to_top: true
                widget: "list"
                fields:
                  - {label: "Название документа", name: "title", widget: "string"}
                  - {label: "Документ", name: "url", widget: "file"}
      - label: "Методические материалы"
        name: "materials"
        file: "_data/materials.yml"
        fields:
          - label: "Блоки документов"
            name: "sections"
            allow_add: true
            add_to_top: true
            widget: "list"
            fields:
              - label: "Id"
                name: "id"
                widget: "number"
              - label: "Название блока документов"
                name: "header"
                widget: "string"
              - label: "Якорь"
                name: "anchor"
                widget: "string"
              - label: "Документы"
                name: "materials"
                allow_add: true
                add_to_top: true
                widget: "list"
                fields:
                  - {label: "Дата", name: "date", widget: "date", default: " ", format: 'MMM Do YY' }
                  - {label: "Название документа", name: "title", widget: "string"}
                  - {label: "Документ", name: "url", widget: "file"}
      - label: "Об организации"
        name: "sections"
        file: "_data/organisation-info.yml"
        fields:
          - label: "Блоки документов"
            name: "sections"
            allow_add: true
            add_to_top: true
            widget: "list"
            fields:
              - label: "Название блока документов"
                name: "header"
                widget: "string"
              - label: "Якорь"
                name: "anchor"
                widget: "string"
              - label: "Абзацы"
                name: "paragraphs"
                allow_add: true
                add_to_top: true
                widget: "list"
                fields:
                  - {label: "Текст", name: "text", widget: "text"}
                  - {label: "Ссылка", name: "link", default: "", widget: "string"}
                  - {label: "Название ссылки", name: "linkName", default: "", widget: "string"}
              - label: "Список файлов (Опционально)"
                name: "list"
                allow_add: true
                add_to_top: true
                widget: "list"
                fields:
                  - {label: "Имя файла", name: "name", default: "", widget: "string"}
                  - {label: "Файл", name: "file", default: "", widget: "file"}
